<a href="https://colab.research.google.com/github/depplenny/zero_to_gans/blob/master/implement_conv2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook demenstrate a simple convolutional opearation in CNN to extact featuers to identify a "X" image. Given M by M input image, P padding, N by N kernal, S stride, CNN outputs a (M+2P-N)/S+1 by (M+2P-N)/S+1 image.

Dimension: output = (input+2padding-kernel)/stride+1

One filter consists of several kernals, e.g. if you apply a filter to a 3\*32\*32 (channel\*width\*height) input image (input feature map), you will need a filter with 3 kernals, apply each kernal to each channel of the image then add all results, you get one channel of the output image (output feature map). With another filter you will get another channel of the output image (output feature map) by repeating the previous step. The output image is not a classical image, it's a collection of features of the input image.

In [ ]:
import numpy as np

In [ ]:
input_1=-1*np.ones((7,7))
i=0
for row in input_1:
    row[i]=1
    row[-(i+1)]=1
    i=i+1
input_1

array([[ 1., -1., -1., -1., -1., -1.,  1.],
       [-1.,  1., -1., -1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1., -1., -1.],
       [-1., -1.,  1., -1.,  1., -1., -1.],
       [-1.,  1., -1., -1., -1.,  1., -1.],
       [ 1., -1., -1., -1., -1., -1.,  1.]])

In [ ]:
input_2=np.array([[ -1., -1., -1., -1., -1., -1.,  1.],
       [1.,  -1., -1., -1., -1.,  1., -1.],
       [-1., 1.,  1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1., -1., -1.],
       [-1., -1.,  1., -1.,  1., 1., -1.],
       [-1.,  -1., 1., -1., -1.,  -1., 1.],
       [ -1., 1., -1., -1., -1., -1.,  -1.]]) 
input_2

array([[-1., -1., -1., -1., -1., -1.,  1.],
       [ 1., -1., -1., -1., -1.,  1., -1.],
       [-1.,  1.,  1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1., -1., -1.],
       [-1., -1.,  1., -1.,  1.,  1., -1.],
       [-1., -1.,  1., -1., -1., -1.,  1.],
       [-1.,  1., -1., -1., -1., -1., -1.]])

In [ ]:
f1=-1*np.ones((3,3))
i=0
for row in f1:
    row[i]=1
    i=i+1
f1

array([[ 1., -1., -1.],
       [-1.,  1., -1.],
       [-1., -1.,  1.]])

In [ ]:
f2=np.array([[1,-1,1],[-1,1,-1],[1,-1,1]])
f2

array([[ 1, -1,  1],
       [-1,  1, -1],
       [ 1, -1,  1]])

In [ ]:
f3=np.array([[-1,-1,1],[-1,1,-1],[1,-1,-1]])
f3

array([[-1, -1,  1],
       [-1,  1, -1],
       [ 1, -1, -1]])

In [ ]:
def convolution(input, f, s):
  #input: input matrix; f: filter matrix, s: stride 
  d_feature_map=(len(input)-len(f))//s+1
  feature_map=np.zeros((d_feature_map,d_feature_map)) 
  for i in range(d_feature_map):
    for j in range(d_feature_map):
      m=i*s 
      n=j*s 
      patch = input[m:m+len(f),n:n+len(f)] 
      feature_map_element=(patch*f).sum()
      feature_map[i,j]=feature_map_element
  return feature_map

In [ ]:
print(convolution(input_1,f1,2))
print("--------------------------------------")
print(convolution(input_2,f1,2))

[[9. 3. 1.]
 [3. 5. 3.]
 [1. 3. 9.]]
--------------------------------------
[[ 1.  3.  1.]
 [ 1.  5.  1.]
 [-3.  1.  1.]]


In [ ]:
print(convolution(input_1,f2,2))
print("--------------------------------------")
print(convolution(input_2,f2,2))

[[5. 3. 5.]
 [3. 9. 3.]
 [5. 3. 5.]]
--------------------------------------
[[-3.  3.  5.]
 [ 1.  9.  1.]
 [-3.  1. -3.]]


In [ ]:
print(convolution(input_1,f3,2))
print("--------------------------------------")
print(convolution(input_2,f3,2))

[[1. 3. 9.]
 [3. 5. 3.]
 [9. 3. 1.]]
--------------------------------------
[[-3.  3.  9.]
 [ 1.  5.  1.]
 [ 1.  1. -3.]]


In [ ]:
def drop(feature_map,limit):
  for i in range(len(feature_map)):
    for j in range(len(feature_map)):
      if feature_map[i,j] < limit:
        feature_map[i,j]=0
      else:
        feature_map[i,j]=1
  return feature_map


In [ ]:
feature_map_1=convolution(input_1,f1,2)
feature_map_1=feature_map_1/feature_map_1.sum()
print("feature_map_1 of input_1:")
print(drop(feature_map_1,0.1)) 

feature_map_1 of input_1:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
feature_map_2=convolution(input_1,f2,2)
feature_map_2=feature_map_2/feature_map_2.sum()
print("feature_map_2 of input_1:")
print(drop(feature_map_2,0.1))

feature_map_2 of input_1:
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [ ]:
feature_map_3=convolution(input_1,f3,2)
feature_map_3=feature_map_3/feature_map_3.sum()
print("feature_map_3 of input_1:")
print(drop(feature_map_3,0.1))

feature_map_3 of input_1:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
